### ISSUE TITLE
TLE parsing fails for QO-100

### ISSUE THREAD

**Issue by schrockwell** [gavineadie/SatelliteKit#6]
I found this problematic TLE in the [AMSAT daily TLEs](https://www.amsat.org/tle/current/dailytle.txt).

```
QO-100
1 43700U 18090A   24234.70209558  .00000136  00000-0  00000 0 0  9992
2 43700   0.0180 170.5287 0002632  15.1180  63.4279  1.00272763 21253
```

The problem is in line 1. There is no sign for the exponent of the drag coefficient.  I assume this is because QO-100 is geostationary.

```
1 43700U 18090A   24234.70209558  .00000136  00000-0  00000 0 0  9992
                                            NO SIGN -------^
```

This causes the conversion from String to Double to fail.

```swift
        stringlet = (lineOneBytes[53] == 32 ||
                     lineOneBytes[53] == 43 ? "+" : "-") + "." +
                    String(bytes: lineOneBytes[54...54], encoding: .utf8)! +
                    String(bytes: lineOneBytes[55...58], encoding: .utf8)! + "e" +
                    String(bytes: lineOneBytes[59...60], encoding: .utf8)!
        self.dragCoeff = Double(stringlet)!  // <-- stringlet is "+.00000e 0"
```

**Comment by gavineadie** [comment]
Thanks for the report. I'll attend to that as soon as I'm near a computer again .. ~24 hours.

**Comment by gavineadie** [comment]
FIXED ..

I've never seen a blank character for the sign of the BTERM exponent before.  This case illustrates it's clearly possible, however, so I appreciate the bug report.
